AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LingoHammer Backend API Setup

Parameters:
  ParentStackName:
    Description: Stack Name
    Type: String
    Default: none


Globals:
  Function:
    Timeout: 20
    MemorySize: 2048
    Runtime: java17
    CodeUri: ../.
    AutoPublishAlias: live
    DeploymentPreference:
      Type: AllAtOnce
    SnapStart:
      ApplyOn: PublishedVersions
    Architectures:
      - x86_64
    Environment: 
      Variables:
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 
        STACK_NAME: !Sub '${ParentStackName}'
      #ReservedConcurrentExecutions: 100
      #ProvisionedConcurrencyConfig:
      #ProvisionedConcurrentExecutions: 1


Resources:

  LingoHammerApiFunction:
    Type: AWS::Serverless::Function 
    Properties:     
      Handler: com.lingohammer.aws.api.ApiServiceHandler::handleRequest
      Events:
        LingoHammer:
          Type: Api 
          Properties:
            Path: /api/{proxy+}
            Method: ANY
    
 
Outputs:
  LingoHammerBackendArn:
    Value: !GetAtt LingoHammerApiFunction.Arn
    Export:
      Name: LingoHammerBackendArn